"""TIN review command bridge for CorridorRoad v1."""

from __future__ import annotations

try:
    import FreeCAD as App
    import FreeCADGui as Gui
except Exception:  # pragma: no cover - FreeCAD is not available in test env.
    App = None
    Gui = None

from ..models.result.tin_surface import (
    TINProvenanceRow,
    TINQualityRow,
    TINSurface,
    TINTriangle,
    TINVertex,
)
from ..services.builders import TINBuildService
from ..services.evaluation import TinSamplingService
from ..services.mapping import (
    TINMeshPreviewMapper,
    enrich_tin_review_preview,
    format_tin_review_summary,
)
from ..ui.viewers import TinReviewViewerTaskPanel


def build_demo_tin_review(
    document_label: str = "",
    *,
    probe_x: float = 5.0,
    probe_y: float = 5.0,
) -> dict[str, object]:
    """Build a small in-memory TIN review payload."""

    surface = TINSurface(
        schema_version=1,
        project_id="corridorroad-v1-demo",
        surface_id="tin:v1-demo-existing-ground",
        surface_kind="existing_ground_tin",
        label=document_label or "CorridorRoad v1 Demo TIN",
        vertex_rows=[
            TINVertex("v0", 0.0, 0.0, 10.0, source_point_ref="demo:p0"),
            TINVertex("v1", 10.0, 0.0, 12.0, source_point_ref="demo:p1"),
            TINVertex("v2", 10.0, 10.0, 15.0, source_point_ref="demo:p2"),
            TINVertex("v3", 0.0, 10.0, 11.0, source_point_ref="demo:p3"),
        ],
        triangle_rows=[
            TINTriangle("t0", "v0", "v1", "v2"),
            TINTriangle("t1", "v0", "v2", "v3"),
        ],
        boundary_refs=["boundary:demo-square"],
        quality_rows=[
            TINQualityRow("quality:triangle-count", "triangle_count", 2, "count"),
            TINQualityRow("quality:vertex-count", "vertex_count", 4, "count"),
        ],
        provenance_rows=[
            TINProvenanceRow(
                "provenance:demo",
                "demo_surface",
                "in_memory",
                "Generated by v1 TIN review bridge.",
            )
        ],
    )
    return build_tin_review(surface, probe_x=probe_x, probe_y=probe_y)


def build_tin_review(
    surface: TINSurface,
    *,
    probe_x: float = 0.0,
    probe_y: float = 0.0,
) -> dict[str, object]:
    """Build a review payload from one TIN surface contract."""

    sample_result = TinSamplingService().sample_xy(
        surface=surface,
        x=float(probe_x),
        y=float(probe_y),
    )
    preview: dict[str, object] = {
        "tin_surface": surface,
        "probe": {"x": float(probe_x), "y": float(probe_y)},
        "sample_result": sample_result,
    }
    return enrich_tin_review_preview(preview)


def build_csv_tin_review(
    path: str,
    *,
    project_id: str = "corridorroad-v1-csv",
    surface_id: str = "tin:csv",
    probe_x: float | None = None,
    probe_y: float | None = None,
) -> dict[str, object]:
    """Build a review payload from a CSV point-cloud TIN source."""

    surface = TINBuildService().build_from_csv(
        path,
        project_id=project_id,
        surface_id=surface_id,
    )
    if probe_x is None or probe_y is None:
        probe_x, probe_y = _surface_probe_center(surface)
    return build_tin_review(surface, probe_x=float(probe_x), probe_y=float(probe_y))


def build_document_tin_review(
    document,
    *,
    gui_module=Gui,
    probe_x: float | None = None,
    probe_y: float | None = None,
) -> dict[str, object] | None:
    """Build a TIN review from a selected or first mesh/shape surface object."""

    surface_obj = _selected_surface_object(gui_module, document)
    if surface_obj is None:
        return None

    surface = _tin_surface_from_object(surface_obj)
    if surface is None:
        return None

    if probe_x is None or probe_y is None:
        probe_x, probe_y = _surface_probe_center(surface)
    return build_tin_review(surface, probe_x=float(probe_x), probe_y=float(probe_y))


def format_tin_review(preview: dict[str, object]) -> str:
    """Format a concise human-readable TIN review summary."""

    return format_tin_review_summary(enrich_tin_review_preview(preview))


def show_v1_tin_review(
    document=None,
    *,
    extra_context: dict[str, object] | None = None,
    app_module=App,
    gui_module=Gui,
) -> dict[str, object]:
    """Build and show one v1 TIN review payload."""

    document_label = ""
    if document is None and app_module is not None:
        document = getattr(app_module, "ActiveDocument", None)
    if document is not None:
        document_label = str(getattr(document, "Label", "") or "")

    probe_x = None
    probe_y = None
    if extra_context:
        try:
            if extra_context.get("probe_x", None) is not None:
                probe_x = float(extra_context.get("probe_x"))
            if extra_context.get("probe_y", None) is not None:
                probe_y = float(extra_context.get("probe_y"))
        except Exception:
            probe_x = None
            probe_y = None

    preview = None
    csv_path = str((extra_context or {}).get("csv_path", "") or "").strip()
    if csv_path:
        preview = build_csv_tin_review(
            csv_path,
            project_id=str((extra_context or {}).get("project_id", "") or "corridorroad-v1-csv"),
            surface_id=str((extra_context or {}).get("surface_id", "") or "tin:csv"),
            probe_x=probe_x,
            probe_y=probe_y,
        )
    if preview is None and document is not None:
        preview = build_document_tin_review(
            document,
            gui_module=gui_module,
            probe_x=probe_x,
            probe_y=probe_y,
        )
    if preview is None:
        preview = build_demo_tin_review(
            document_label=document_label,
            probe_x=5.0 if probe_x is None else probe_x,
            probe_y=5.0 if probe_y is None else probe_y,
        )
    if extra_context:
        preview.update(dict(extra_context))
        preview = enrich_tin_review_preview(preview)

    if _should_create_mesh_preview(document, extra_context):
        preview["mesh_preview"] = TINMeshPreviewMapper().create_preview_object(
            document,
            preview["tin_surface"],
        )
        _route_mesh_preview_to_v1_tree(document, preview["mesh_preview"])
        preview = enrich_tin_review_preview(preview)

    _route_tin_records_to_v1_tree(document, preview)

    summary_text = str(preview.get("summary_text", "") or format_tin_review(preview))
    if app_module is not None:
        app_module.Console.PrintMessage(summary_text + "\n")

    if gui_module is not None and hasattr(gui_module, "Control"):  # pragma: no branch - GUI path only in FreeCAD.
        try:
            _focus_tin_preview_object(document, preview, gui_module=gui_module)
            _show_tin_complete_message(preview, gui_module=gui_module)
            gui_module.Control.showDialog(TinReviewViewerTaskPanel(preview))
        except Exception:
            try:  # pragma: no cover - GUI fallback not available in tests.
                from PySide import QtGui

                QtGui.QMessageBox.information(
                    None,
                    "CorridorRoad v1 TIN Review",
                    summary_text,
                )
            except Exception:
                pass

    return preview


def _focus_tin_preview_object(document, preview: dict[str, object], *, gui_module=Gui) -> bool:
    """Select and center the generated TIN mesh preview in the active 3D view."""

    if document is None or gui_module is None:
        return False
    mesh_preview = preview.get("mesh_preview") if isinstance(preview, dict) else None
    object_name = str(getattr(mesh_preview, "object_name", "") or "").strip()
    if not object_name:
        return False
    obj = document.getObject(object_name)
    if obj is None:
        return False
    try:
        if hasattr(gui_module, "Selection"):
            gui_module.Selection.clearSelection()
            gui_module.Selection.addSelection(obj)
    except Exception:
        pass
    try:
        view = gui_module.ActiveDocument.ActiveView
        if hasattr(view, "viewIsometric"):
            view.viewIsometric()
    except Exception:
        try:
            gui_module.SendMsgToActiveView("ViewAxo")
        except Exception:
            pass
    try:
        view = gui_module.ActiveDocument.ActiveView
        if hasattr(view, "fitSelection"):
            view.fitSelection()
        else:
            gui_module.SendMsgToActiveView("ViewSelection")
    except Exception:
        try:
            gui_module.SendMsgToActiveView("ViewSelection")
        except Exception:
            try:
                gui_module.ActiveDocument.ActiveView.fitAll()
            except Exception:
                return False
    return True


def _show_tin_complete_message(preview: dict[str, object], *, gui_module=Gui) -> None:
    """Show a compact completion message after PointCloud TIN generation."""

    if gui_module is None:
        return
    try:
        mesh_preview = preview.get("mesh_preview") if isinstance(preview, dict) else None
        mesh_status = str(getattr(mesh_preview, "status", "") or "not created")
        mesh_name = str(getattr(mesh_preview, "label", "") or getattr(mesh_preview, "object_name", "") or "")
        surface = preview.get("tin_surface") if isinstance(preview, dict) else None
        vertex_count = len(list(getattr(surface, "vertex_rows", []) or []))
        triangle_count = len(list(getattr(surface, "triangle_rows", []) or []))
        message = (
            "PointCloud TIN 작업이 완료되었습니다.\n"
            f"Mesh preview: {mesh_status}"
            + (f"\nObject: {mesh_name}" if mesh_name else "")
            + f"\nVertices: {vertex_count}"
            + f"\nTriangles: {triangle_count}"
        )
        from freecad.Corridor_Road.qt_compat import QtWidgets

        QtWidgets.QMessageBox.information(None, "PointCloud TIN", message)
    except Exception:
        pass


def _should_create_mesh_preview(document, extra_context: dict[str, object] | None) -> bool:
    """Return whether a mesh preview should be attempted for this review."""

    if document is None:
        return False
    value = (extra_context or {}).get("create_mesh_preview", True)
    return bool(value)


def _route_mesh_preview_to_v1_tree(document, mesh_preview) -> None:
    """Place mesh preview objects under the v1 Existing Ground TIN preview folder."""

    if document is None or mesh_preview is None:
        return
    if str(getattr(mesh_preview, "status", "") or "") != "created":
        return
    object_name = str(getattr(mesh_preview, "object_name", "") or "").strip()
    if not object_name:
        return
    try:
        from freecad.Corridor_Road.objects.obj_project import (
            V1_TREE_EXISTING_GROUND_TIN_MESH_PREVIEW,
            ensure_project_tree,
            find_project,
        )

        project = find_project(document)
        if project is None:
            return
        tree = ensure_project_tree(project, include_references=False)
        folder = tree.get(V1_TREE_EXISTING_GROUND_TIN_MESH_PREVIEW, None)
        obj = document.getObject(object_name)
        if folder is not None and obj is not None:
            _set_string_property(obj, "CRRecordKind", "tin_mesh_preview")
            _move_to_tree_folder(project, folder, obj)
    except Exception:
        return


def _route_tin_records_to_v1_tree(document, preview: dict[str, object]) -> None:
    """Create v1 tree metadata records for TIN source, result, and diagnostics."""

    if document is None or not preview:
        return
    surface = preview.get("tin_surface")
    if surface is None:
        return
    try:
        from freecad.Corridor_Road.objects.obj_project import (
            V1_TREE_EXISTING_GROUND_TIN_DIAGNOSTICS,
            V1_TREE_EXISTING_GROUND_TIN_RESULT,
            V1_TREE_EXISTING_GROUND_TIN_SOURCE,
            V1_TREE_SURVEY_POINTS,
            ensure_project_tree,
            find_project,
        )

        project = find_project(document)
        if project is None:
            return
        tree = ensure_project_tree(project, include_references=False)
        source_record = _ensure_tin_source_record(document, preview)
        surface_source_record = _ensure_tin_surface_source_record(document, preview)
        result_record = _ensure_tin_result_record(document, preview)
        diagnostics_record = _ensure_tin_diagnostics_record(document, preview)

        _move_to_tree_folder(project, tree.get(V1_TREE_SURVEY_POINTS, None), source_record)
        _move_to_tree_folder(project, tree.get(V1_TREE_EXISTING_GROUND_TIN_SOURCE, None), surface_source_record)
        _move_to_tree_folder(project, tree.get(V1_TREE_EXISTING_GROUND_TIN_RESULT, None), result_record)
        _move_to_tree_folder(project, tree.get(V1_TREE_EXISTING_GROUND_TIN_DIAGNOSTICS, None), diagnostics_record)
        preview["tree_records"] = {
            "source": str(getattr(source_record, "Name", "") or ""),
            "surface_source": str(getattr(surface_source_record, "Name", "") or ""),
            "result": str(getattr(result_record, "Name", "") or ""),
            "diagnostics": str(getattr(diagnostics_record, "Name", "") or ""),
        }
    except Exception:
        return


def _ensure_tin_source_record(document, preview: dict[str, object]):
    surface = preview.get("tin_surface")
    source = str(preview.get("tin_source", "") or "").strip()
    surface_id = str(getattr(surface, "surface_id", "") or "tin")
    name = f"CRV1_TIN_Source_{_safe_name_token(surface_id)}"
    obj = _get_or_create_metadata_object(document, name, f"Source CSV - {_short_source_name(source)}")
    _set_string_property(obj, "CRRecordKind", "tin_source_csv")
    _set_string_property(obj, "SurfaceId", surface_id)
    _set_string_property(obj, "SourcePath", source)
    return obj


def _ensure_tin_surface_source_record(document, preview: dict[str, object]):
    surface = preview.get("tin_surface")
    source = str(preview.get("tin_source", "") or "").strip()
    surface_id = str(getattr(surface, "surface_id", "") or "tin")
    name = f"CRV1_TIN_Surface_Source_{_safe_name_token(surface_id)}"
    obj = _get_or_create_metadata_object(document, name, f"TIN Source - {_short_source_name(source)}")
    _set_string_property(obj, "CRRecordKind", "tin_surface_source")
    _set_string_property(obj, "SurfaceId", surface_id)
    _set_string_property(obj, "SourcePath", source)
    _set_string_property(obj, "SourceRecordName", f"CRV1_TIN_Source_{_safe_name_token(surface_id)}")
    return obj


def _ensure_tin_result_record(document, preview: dict[str, object]):
    surface = preview.get("tin_surface")
    surface_id = str(getattr(surface, "surface_id", "") or "tin")
    name = f"CRV1_TIN_Result_{_safe_name_token(surface_id)}"
    obj = _get_or_create_metadata_object(document, name, f"TIN Result - {surface_id}")
    _set_string_property(obj, "CRRecordKind", "tin_surface_result")
    _set_string_property(obj, "SurfaceId", surface_id)
    _set_string_property(obj, "SurfaceKind", str(getattr(surface, "surface_kind", "") or ""))
    _set_integer_property(obj, "VertexCount", len(list(getattr(surface, "vertex_rows", []) or [])))
    _set_integer_property(obj, "TriangleCount", len(list(getattr(surface, "triangle_rows", []) or [])))
    return obj


def _ensure_tin_diagnostics_record(document, preview: dict[str, object]):
    surface = preview.get("tin_surface")
    surface_id = str(getattr(surface, "surface_id", "") or "tin")
    extent = dict(preview.get("tin_extent", {}) or {})
    name = f"CRV1_TIN_Diagnostics_{_safe_name_token(surface_id)}"
    obj = _get_or_create_metadata_object(document, name, f"TIN Diagnostics - {surface_id}")
    _set_string_property(obj, "CRRecordKind", "tin_diagnostics")
    _set_string_property(obj, "SurfaceId", surface_id)
    _set_string_property(obj, "ProbeExtentStatus", str(preview.get("probe_extent_status", "") or ""))
    _set_string_property(obj, "ProbeGuidance", str(preview.get("probe_guidance", "") or ""))
    for prop_name, key in (
        ("XMin", "x_min"),
        ("XMax", "x_max"),
        ("YMin", "y_min"),
        ("YMax", "y_max"),
        ("ZMin", "z_min"),
        ("ZMax", "z_max"),
    ):
        _set_float_property(obj, prop_name, extent.get(key, 0.0))
    _set_string_property(obj, "XSpacing", str(extent.get("x_spacing", "") or ""))
    _set_string_property(obj, "YSpacing", str(extent.get("y_spacing", "") or ""))
    return obj


def _get_or_create_metadata_object(document, name: str, label: str):
    obj = document.getObject(name)
    if obj is None:
        obj = document.addObject("App::FeaturePython", name)
    try:
        obj.Label = label
    except Exception:
        pass
    return obj


def _add_to_tree_folder(folder, obj) -> None:
    if folder is None or obj is None:
        return
    try:
        folder.addObject(obj)
    except Exception:
        children = list(getattr(folder, "Group", []) or [])
        if obj not in children:
            folder.Group = children + [obj]


def _move_to_tree_folder(project, folder, obj) -> None:
    """Move an object to one v1 tree folder, removing stale duplicate folder memberships."""

    if project is None or folder is None or obj is None:
        return
    for owner in [project] + list(_iter_tree_folders(project)):
        if owner is None or owner == folder or owner == obj:
            continue
        try:
            owner.removeObject(obj)
        except Exception:
            try:
                children = list(getattr(owner, "Group", []) or [])
                if obj in children:
                    owner.Group = [child for child in children if child != obj]
            except Exception:
                pass
    _add_to_tree_folder(folder, obj)


def _iter_tree_folders(root):
    pending = list(getattr(root, "Group", []) or [])
    seen = set()
    while pending:
        obj = pending.pop(0)
        name = str(getattr(obj, "Name", "") or "")
        if not name or name in seen:
            continue
        seen.add(name)
        if hasattr(obj, "Group"):
            yield obj
            pending.extend(list(getattr(obj, "Group", []) or []))


def _set_string_property(obj, name: str, value: str) -> None:
    if obj is None:
        return
    if not hasattr(obj, name):
        obj.addProperty("App::PropertyString", name, "CorridorRoad", name)
    setattr(obj, name, str(value or ""))


def _set_integer_property(obj, name: str, value: int) -> None:
    if obj is None:
        return
    if not hasattr(obj, name):
        obj.addProperty("App::PropertyInteger", name, "CorridorRoad", name)
    setattr(obj, name, int(value or 0))


def _set_float_property(obj, name: str, value) -> None:
    if obj is None:
        return
    if not hasattr(obj, name):
        obj.addProperty("App::PropertyFloat", name, "CorridorRoad", name)
    try:
        setattr(obj, name, float(value))
    except Exception:
        setattr(obj, name, 0.0)


def _safe_name_token(value: str) -> str:
    raw = str(value or "tin").strip()
    safe = "".join(ch if ch.isalnum() else "_" for ch in raw)
    return (safe.strip("_") or "tin")[:80]


def _short_source_name(source: str) -> str:
    text = str(source or "").replace("\\", "/").rstrip("/")
    if not text:
        return "(unknown)"
    return text.split("/")[-1] or text


def run_v1_tin_review_command() -> dict[str, object]:
    """Execute the minimal v1 TIN review bridge."""

    return show_v1_tin_review(app_module=App, gui_module=Gui)


class CmdV1ReviewTin:
    """Standalone v1 TIN review command."""

    def GetResources(self):
        from freecad.Corridor_Road.misc.resources import icon_path

        return {
            "Pixmap": icon_path("pointcloud_tin.svg"),
            "MenuText": "TIN Review (v1)",
            "ToolTip": "Run the v1 TIN review pipeline",
        }

    def IsActive(self):
        return App is not None and getattr(App, "ActiveDocument", None) is not None

    def Activated(self):
        run_v1_tin_review_command()


def _selected_surface_object(gui_module, document):
    if document is None:
        return None
    selected = []
    if gui_module is not None:
        try:
            selected = list(gui_module.Selection.getSelection() or [])
        except Exception:
            selected = []

    candidates = selected + list(getattr(document, "Objects", []) or [])
    for obj in candidates:
        if _is_surface_like(obj):
            return obj
    return None


def _is_surface_like(obj) -> bool:
    try:
        from freecad.Corridor_Road.objects import surface_sampling_core as _ssc

        return bool(_ssc.is_mesh_object(obj) or _ssc.is_shape_object(obj))
    except Exception:
        return False


def _tin_surface_from_object(obj, max_triangles: int = 10000) -> TINSurface | None:
    try:
        from freecad.Corridor_Road.objects import surface_sampling_core as _ssc
    except Exception:
        return None

    if _ssc.is_mesh_object(obj):
        raw_triangles = _ssc.mesh_triangles(obj)
        source_kind = "mesh"
    elif _ssc.is_shape_object(obj):
        raw_triangles = _ssc.shape_triangles(obj)
        source_kind = "shape"
    else:
        return None
    if not raw_triangles:
        return None

    triangles = raw_triangles[: max(1, int(max_triangles))]
    vertices: list[TINVertex] = []
    vertex_index: dict[tuple[float, float, float], str] = {}
    triangle_rows: list[TINTriangle] = []

    def vertex_id_for(point) -> str:
        key = (round(float(point.x), 9), round(float(point.y), 9), round(float(point.z), 9))
        existing = vertex_index.get(key)
        if existing is not None:
            return existing
        vertex_id = f"v{len(vertices)}"
        vertex_index[key] = vertex_id
        vertices.append(TINVertex(vertex_id, float(point.x), float(point.y), float(point.z)))
        return vertex_id

    for index, triangle in enumerate(triangles):
        p0, p1, p2 = triangle[0], triangle[1], triangle[2]
        triangle_rows.append(
            TINTriangle(
                f"t{index}",
                vertex_id_for(p0),
                vertex_id_for(p1),
                vertex_id_for(p2),
            )
        )

    label = str(getattr(obj, "Label", "") or getattr(obj, "Name", "") or "TIN Surface")
    name = str(getattr(obj, "Name", "") or label.replace(" ", "_") or "surface")
    return TINSurface(
        schema_version=1,
        project_id="corridorroad-v1-document",
        surface_id=f"tin:{name}",
        surface_kind="existing_ground_tin",
        label=label,
        vertex_rows=vertices,
        triangle_rows=triangle_rows,
        quality_rows=[
            TINQualityRow("quality:triangle-count", "triangle_count", len(triangle_rows), "count"),
            TINQualityRow("quality:vertex-count", "vertex_count", len(vertices), "count"),
        ],
        provenance_rows=[
            TINProvenanceRow(
                "provenance:document-object",
                source_kind,
                name,
                "Extracted from selected FreeCAD document surface for review.",
            )
        ],
    )


def _surface_probe_center(surface: TINSurface) -> tuple[float, float]:
    vertices = list(surface.vertex_rows or [])
    if not vertices:
        return 0.0, 0.0
    x_values = [float(row.x) for row in vertices]
    y_values = [float(row.y) for row in vertices]
    return (
        (min(x_values) + max(x_values)) * 0.5,
        (min(y_values) + max(y_values)) * 0.5,
    )


if Gui is not None and hasattr(Gui, "addCommand"):  # pragma: no cover - FreeCAD registration only.
    Gui.addCommand("CorridorRoad_V1ReviewTin", CmdV1ReviewTin())
